from abc import ABC, abstractmethod
from typing import Any
class AIService(ABC):
    @abstractmethod
    def extract_resume(self, career_text:str)->dict: ...
    @abstractmethod
    def extract_job(self, job_text:str)->dict: ...
    @abstractmethod
    def generate_embedding(self, text:str)->list[float]: ...
    @abstractmethod
    def assess_candidate_job_match(self,candidate:dict,job:dict)->dict: ...
    @abstractmethod
    def explain_match(self,match:dict)->str: ...
    @abstractmethod
    def classify_feedback(self,text:str)->dict: ...
