"""initial schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0001'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    for table, cols in [
      ('users', [('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('email','VARCHAR(320) UNIQUE NOT NULL'),('name','VARCHAR(200)'),('phone','VARCHAR(50)'),('is_active','BOOLEAN NOT NULL DEFAULT TRUE'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('candidate_profiles',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('user_id','UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE'),('current_role','VARCHAR(200)'),('years_experience','DOUBLE PRECISION'),('skills','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('technologies','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('companies','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('education','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('certifications','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('career_direction','TEXT'),('target_roles','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('previous_roles','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('career_preferences',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('user_id','UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE'),('target_roles','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('locations','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('relocation_preference','VARCHAR(50)'),('work_modes','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('min_compensation','DOUBLE PRECISION'),('max_compensation','DOUBLE PRECISION'),('compensation_currency','VARCHAR(10)'),('industries','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('preferred_companies','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('deal_breakers','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('job_priorities','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('resumes',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('user_id','UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE'),('storage_key','VARCHAR(500) NOT NULL'),('filename','VARCHAR(255) NOT NULL'),('content_type','VARCHAR(100) NOT NULL'),('extracted_text','TEXT'),('extraction_status','VARCHAR(30) NOT NULL'),('is_current','BOOLEAN NOT NULL DEFAULT TRUE'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('companies',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('canonical_name','VARCHAR(300) UNIQUE NOT NULL'),('display_name','VARCHAR(300) NOT NULL'),('website','VARCHAR(500)'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('job_sources',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('name','VARCHAR(100) UNIQUE NOT NULL'),('status','VARCHAR(20) NOT NULL'),('last_health_check_at','TIMESTAMPTZ'),('last_refresh_at','TIMESTAMPTZ'),('metadata_json','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('jobs',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('canonical_id','VARCHAR(100) UNIQUE NOT NULL'),('company_id','UUID REFERENCES companies(id)'),('title','VARCHAR(500) NOT NULL'),('original_title','VARCHAR(500) NOT NULL'),('description','TEXT NOT NULL'),('skills','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('experience_min','DOUBLE PRECISION'),('experience_max','DOUBLE PRECISION'),('locations','JSONB NOT NULL DEFAULT \'[]\'::jsonb'),('work_mode','VARCHAR(50)'),('salary_min','DOUBLE PRECISION'),('salary_max','DOUBLE PRECISION'),('salary_currency','VARCHAR(10)'),('employment_type','VARCHAR(50)'),('posted_at','TIMESTAMPTZ'),('source_updated_at','TIMESTAMPTZ'),('first_seen_at','TIMESTAMPTZ NOT NULL'),('last_seen_at','TIMESTAMPTZ NOT NULL'),('status','VARCHAR(20) NOT NULL'),('source_url','VARCHAR(1000)'),('application_url','VARCHAR(1000)'),('source_data','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('ai_enrichment','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('credibility_signals','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('external_job_references',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('job_id','UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE'),('source_id','UUID NOT NULL REFERENCES job_sources(id) ON DELETE CASCADE'),('source_job_id','VARCHAR(500) NOT NULL'),('source_url','VARCHAR(1000)'),('raw_payload','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('last_seen_at','TIMESTAMPTZ NOT NULL'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('job_embeddings',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('job_id','UUID UNIQUE NOT NULL REFERENCES jobs(id) ON DELETE CASCADE'),('model_name','VARCHAR(100) NOT NULL'),('vector_json','JSONB'),('source_hash','VARCHAR(128)'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('job_matches',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('user_id','UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE'),('job_id','UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE'),('match_status','VARCHAR(50) NOT NULL'),('score','DOUBLE PRECISION NOT NULL'),('signals','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('hard_filter_results','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('explanation_inputs','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('recommendations',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('user_id','UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE'),('job_id','UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE'),('match_id','UUID NOT NULL REFERENCES job_matches(id) ON DELETE CASCADE'),('rank_position','INTEGER NOT NULL'),('match_label','VARCHAR(50) NOT NULL'),('explanation','TEXT'),('status','VARCHAR(20) NOT NULL'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('user_interactions',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('user_id','UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE'),('job_id','UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE'),('interaction_type','VARCHAR(40) NOT NULL'),('metadata_json','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')]),
      ('recommendation_feedback',[('id','UUID PRIMARY KEY DEFAULT gen_random_uuid()'),('recommendation_id','UUID NOT NULL REFERENCES recommendations(id) ON DELETE CASCADE'),('user_id','UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE'),('feedback_type','VARCHAR(50) NOT NULL'),('reason','VARCHAR(300)'),('metadata_json','JSONB NOT NULL DEFAULT \'{}\'::jsonb'),('created_at','TIMESTAMPTZ NOT NULL'),('updated_at','TIMESTAMPTZ NOT NULL')])]:
        safe_cols = [
            (f'"{c}"' if c == "current_role" else c, t)
            for c, t in cols
        ]
        op.execute(f"CREATE TABLE {table} ({', '.join(f'{c} {t}' for c,t in safe_cols)})")
    op.execute('CREATE UNIQUE INDEX uq_source_job ON external_job_references(source_id, source_job_id)')
    for sql in ['CREATE INDEX ix_users_email ON users(email)','CREATE INDEX ix_jobs_canonical_id ON jobs(canonical_id)','CREATE INDEX ix_jobs_status ON jobs(status)','CREATE INDEX ix_jobs_last_seen_at ON jobs(last_seen_at)','CREATE INDEX ix_external_job_references_job_id ON external_job_references(job_id)','CREATE INDEX ix_external_job_references_source_id ON external_job_references(source_id)','CREATE INDEX ix_job_matches_user_id ON job_matches(user_id)','CREATE INDEX ix_job_matches_job_id ON job_matches(job_id)','CREATE UNIQUE INDEX uq_user_job_match ON job_matches(user_id, job_id)','CREATE INDEX ix_recommendations_user_id ON recommendations(user_id)','CREATE INDEX ix_recommendations_job_id ON recommendations(job_id)','CREATE INDEX ix_user_interactions_user_id ON user_interactions(user_id)','CREATE INDEX ix_user_interactions_job_id ON user_interactions(job_id)','CREATE INDEX ix_recommendation_feedback_recommendation_id ON recommendation_feedback(recommendation_id)']: op.execute(sql)

def downgrade():
    for t in ['recommendation_feedback','user_interactions','recommendations','job_matches','job_embeddings','external_job_references','jobs','job_sources','companies','resumes','career_preferences','candidate_profiles','users']: op.execute(f'DROP TABLE IF EXISTS {t} CASCADE')
